repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.1
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        # args: [--disable-error-code, union-attr]
        additional_dependencies:
          - aiohttp
          - aiosmtpd
          - nox
          - passlib
          - pymap~=0.36
          - pytest
          - setuptools
          - typing-extensions
